### ISSUE TITLE
Modules which define a class don't work

### ISSUE THREAD

**Issue by aminer-looker** [bminer/module-concat#4]
If I have a module which attempts to change the `module.exports` object to be a function, and it gets clobbered by the change introduced in c9ca37c9ab96815e1a511a2c09a875670c46d694, which copies over the keys, but leaves the original object itself behind.  In this case, that means that the actual constructor function is dropped and replaced by an empty object.

**Comment by bminer** [comment]
Ok. Would you mind posting some succinct sample code exhibiting the problem?

**Comment by aminer-looker** [comment]
Something like the following would suffice:

``` javascript
module.exports = function MyConstructor() {
    this.name = "Untitled";
}
```

You'll find that after concatenating this with another JavaScript file, you won't be able to invoke `new` with the output since it will no longer be a function.

``` javascript
MyConstructor = require './first_file.js';
foo = new MyConstructor(); // Error: MyConstructor is not a function
```

**Comment by bminer** [comment]
OK, would you mind checking out the latest fix before I publish to NPM?  You could do `npm install https://github.com/bminer/node-module-concat.git` or something like that...

Please let me know either way.  Thanks!

**Comment by aminer-looker** [comment]
Works for me!  Thanks!

**Comment by bminer** [comment]
OK, thank you for the bug report. Published to NPM!
